#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

EXPERIMENT_NAME="${EXPERIMENT_NAME:-smoke_wan_compact_i2v14b480p}"
MAX_STEPS="${MAX_STEPS:-2}"
SAVE_EVERY="${SAVE_EVERY:-1}"
EVAL_EVERY="${EVAL_EVERY:-1}"
LOG_EVERY="${LOG_EVERY:-1}"
BATCH_SIZE="${BATCH_SIZE:-1}"
ACCUM_STEPS="${ACCUM_STEPS:-1}"
EXPECTED_NNODES="${EXPECTED_NNODES:-${VC_WORKER_NUM:-1}}"
AUTO_RESUME="${AUTO_RESUME:-0}"
TRAIN_QKV="${TRAIN_QKV:-0}"
MASTER_PORT="${MASTER_PORT:-29625}"

export EXPERIMENT_NAME
export MAX_STEPS SAVE_EVERY EVAL_EVERY LOG_EVERY
export BATCH_SIZE ACCUM_STEPS EXPECTED_NNODES AUTO_RESUME TRAIN_QKV MASTER_PORT

bash "${SCRIPT_DIR}/05_train_wan_compact.sh"
