#!/bin/bash
# Smoke the revised Wan 1.3B anchor-memory path, including PNG/MP4 previews.
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

DIFFUSION_NAMESPACE="${DIFFUSION_NAMESPACE:-smoke_r7_wan13b_anchor_memory_v2}"
MAX_STEPS="${MAX_STEPS:-2}"
SAVE_EVERY="${SAVE_EVERY:-1}"
EVAL_EVERY="${EVAL_EVERY:-1}"
LOG_EVERY="${LOG_EVERY:-1}"
WARMUP_STEPS="${WARMUP_STEPS:-1}"
WAN_FREEZE_STEPS="${WAN_FREEZE_STEPS:-1}"
BATCH_SIZE="${BATCH_SIZE:-1}"
ACCUM_STEPS="${ACCUM_STEPS:-1}"
EVAL_CLIPS="${EVAL_CLIPS:-2}"
SAMPLE_CLIPS="${SAMPLE_CLIPS:-1}"
PREVIEW_CLIPS="${PREVIEW_CLIPS:-1}"
SAMPLE_STEPS="${SAMPLE_STEPS:-4}"
EXPECTED_NNODES="${EXPECTED_NNODES:-${VC_WORKER_NUM:-1}}"
AUTO_RESUME="${AUTO_RESUME:-0}"
MASTER_PORT="${MASTER_PORT:-29686}"

export DIFFUSION_NAMESPACE MAX_STEPS SAVE_EVERY EVAL_EVERY LOG_EVERY
export WARMUP_STEPS WAN_FREEZE_STEPS BATCH_SIZE ACCUM_STEPS EVAL_CLIPS
export SAMPLE_CLIPS PREVIEW_CLIPS SAMPLE_STEPS EXPECTED_NNODES AUTO_RESUME MASTER_PORT

bash "${SCRIPT_DIR}/16_train_wan_t2v_diffusion.sh"
