#!/bin/bash
# 2-step smoke for the Wan2.1-T2V-1.3B full-finetune diffusion stage.
# Verifies WanModel load, text-embedding sidecar lookup, HCCL, fp16 scaler,
# eval decode, and OBS sync before any long run.
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

DIFFUSION_NAMESPACE="${DIFFUSION_NAMESPACE:-smoke_r7_wan13b_t2v}"
MAX_STEPS="${MAX_STEPS:-2}"
SAVE_EVERY="${SAVE_EVERY:-1}"
EVAL_EVERY="${EVAL_EVERY:-1}"
LOG_EVERY="${LOG_EVERY:-1}"
WARMUP_STEPS="${WARMUP_STEPS:-1}"
WAN_FREEZE_STEPS="${WAN_FREEZE_STEPS:-1}"
BATCH_SIZE="${BATCH_SIZE:-1}"
ACCUM_STEPS="${ACCUM_STEPS:-1}"
EVAL_CLIPS="${EVAL_CLIPS:-2}"
SAMPLE_CLIPS="${SAMPLE_CLIPS:-1}"
SAMPLE_STEPS="${SAMPLE_STEPS:-4}"
EXPECTED_NNODES="${EXPECTED_NNODES:-${VC_WORKER_NUM:-1}}"
AUTO_RESUME="${AUTO_RESUME:-0}"
MASTER_PORT="${MASTER_PORT:-29686}"

export DIFFUSION_NAMESPACE
export MAX_STEPS SAVE_EVERY EVAL_EVERY LOG_EVERY WARMUP_STEPS WAN_FREEZE_STEPS
export BATCH_SIZE ACCUM_STEPS EVAL_CLIPS SAMPLE_CLIPS SAMPLE_STEPS
export EXPECTED_NNODES AUTO_RESUME MASTER_PORT

bash "${SCRIPT_DIR}/16_train_wan_t2v_diffusion.sh"
